version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  spark-master:
    image: bitnami/spark:3.1.2
    container_name: spark-master
    environment:
      SPARK_MODE: master
      JAVA_OPTS: "-Djava.awt.headless=true -Dsun.net.inetaddr.ttl=30"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - app-network

  spark-worker-1:
    image: bitnami/spark:3.1.2
    container_name: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
    depends_on:
      - spark-master
    networks:
      - app-network